#!/bin/bash -e
WORKDIR="/var/lib/apt-current/"

# find the command and see if it's one that may require an update check
CMD=""
for var in "$@"
do
    [[ $var == -* ]] || { CMD="$1"; break; }
done	

[[ "${CMD}" == "install" || "${CMD}" == "dist-upgrade" || "${CMD}" == "upgrade" ]] || { apt-get "$@" ; exit $? ; }

PERFORM_UPDATE=false
# check whether our latest apt-get update is too old
. /etc/apt-current.conf
MAXDELTA=${MAXDELTA:-10800}

# either they're true or we must force it to the false literal
[ "true" == "${CLEANUP_DOWNLOADED_PACKAGES}" ] || { CLEANUP_DOWNLOADED_PACKAGES="false" ; }
[ "true" == "${CLEANUP_DOWNLOADED_LISTS}" ] || { CLEANUP_DOWNLOADED_LISTS="false" ; }

CURDATE="$(date +%s)"
PREVDATE=$(cat ${WORKDIR}/timestamp)
[ "$(( ${CURDATE} - ${PREVDATE} ))" -gt "${MAXDELTA}" ] && PERFORM_UPDATE=true

# check whether our sources.list have changed; in this situation, always update
SOURCES="/etc/apt/sources.list $(find /etc/apt/sources.list.d/ -name "*.list" -o -name "*.sources" | sort)"
CURSOURCES_HASH="$(echo $SOURCES | xargs cat | md5sum | cut -f 1 -d ' ')"
[ "${CURSOURCES_HASH}" == "$(cat ${WORKDIR}/latest-sources)" ] || PERFORM_UPDATE=true

CURCONFIG="$(apt-config dump | md5sum | cut -f 1 -d ' ')" 
[ "${CURCONFIG}" == "$(cat ${WORKDIR}/latest-config)" ] || PERFORM_UPDATE=true

${PERFORM_UPDATE} && apt-get -y update

set +e
apt-get "$@"
EXIT_CODE="$?"
${CLEANUP_DOWNLOADED_PACKAGES} && apt-get -y clean
${CLEANUP_DOWNLOADED_LISTS} && rm -f /var/lib/apt/lists/* /var/lib/apt/lists/partial/*
exit ${EXIT_CODE}
