#!/bin/bash -e
WORKDIR="/var/lib/apt-current/"
CMDLINE="$@"

# find the command and see if it's one that may require an update check
CMD=""
while [ -n "$1" ]; do
    [[ $1 == -* ]] || { CMD="$1"; break; }
    shift
done	

[ "${CMD}" == "install" ] || { apt "${CMDLINE}" ; exit $? ; }

PERFORM_UPDATE=false
# check whether our latest apt-get update is too old
. /etc/apt-current.conf
MAXDELTA=${MAXDELTA:-10800}
CURDATE="$(date +%s)"
PREVDATE=$(cat ${WORKDIR}/timestamp)
[ "$(( ${CURDATE} - ${PREVDATE} ))" -gt "${MAXDELTA}" ] && PERFORM_UPDATE=true


#SOURCES="/etc/apt/sources.list $(find /etc/apt/sources.list.d/ -name "*.list" -o -name "*.sources" | sort)"
#CURSOURCES="$(echo $SOURCES | xargs cat | md5sum | cut -f 1 -d ' ')"
#CURCONFIG="$(apt-config dump | md5sum | cut -f 1 -d ' ')" 

#echo "${CURCONFHASH}" > ${WORKDIR}/latest-sources

${PERFORM_UPDATE} && apt -y update
apt "${CMDLINE}"
exit $?
