#!/bin/bash -ex
# we should always set proper ownership before exiting, otherwise
# the created logs will have root:root ownership and we'll be unable
# to delete them from our host.
trap 'chown -R --reference /test-inside/test /test-logs/' EXIT

#we must do this in order to install a deb and missing deps afaik
dpkg -i /out/*.deb || /bin/true
apt-get -f -y install

/test-inside/run_tests $1
