#!/bin/bash -ex

APT_CMD="$1"
# zeroed, since just installed
[ "$(cat /var/lib/apt-current/timestamp)" -eq 0 ]

# this should trigger an update, since it's the first time we launch the tool
${APT_CMD} install -y openssl
CURRENT_TS="$(cat /var/lib/apt-current/timestamp)"
# we assume the install procedure doesn't take more than then minutes
[ "$(( $(date +%s) - ${CURRENT_TS} ))" -lt 600 ]

# this one should NOT trigger an update
${APT_CMD} -y install wget
UPDATED_TS="$(cat /var/lib/apt-current/timestamp)"
[ "${UPDATED_TS}" == "${CURRENT_TS}" ]

echo "MAXDELTA=1" > /etc/apt-current.conf
# now it SHOULD trigger an update
${APT_CMD} install -y curl
UPDATED_TS="$(cat /var/lib/apt-current/timestamp)"
[ "${UPDATED_TS}" -gt "${CURRENT_TS}" ]
CURRENT_TS="${UPDATED_TS}"

echo "MAXDELTA=10800" > /etc/apt-current.conf
curl https://www.franzoni.eu/keys/D401AB61.txt | apt-key add -
echo "deb https://dl.bintray.com/alanfranz/drb-v1-ubuntu-trusty trusty main" > /etc/apt/sources.list.d/drb.list
# now it SHOULD trigget an update because the source listing has changed
${APT_CMD} install -y tcpdump
UPDATED_TS="$(cat /var/lib/apt-current/timestamp)"
[ "${UPDATED_TS}" -gt "${CURRENT_TS}" ]
CURRENT_TS="${UPDATED_TS}"

# now it SHOULD NOT trigger an update because nothing has changed
${APT_CMD} remove -y tcpdump
${APT_CMD} install -y tcpdump
UPDATED_TS="$(cat /var/lib/apt-current/timestamp)"
[ "${UPDATED_TS}" -eq "${CURRENT_TS}" ]

# now it SHOULD trigger an update because config will change
${APT_CMD} remove -y tcpdump
rm -f /etc/apt/apt.conf.d/docker-gzip-indexes
${APT_CMD} install -y tcpdump
UPDATED_TS="$(cat /var/lib/apt-current/timestamp)"
[ "${UPDATED_TS}" -gt "${CURRENT_TS}" ]
CURRENT_TS="${UPDATED_TS}"

# now it SHOULD NOT trigger an update because config is the same
${APT_CMD} remove -y tcpdump
${APT_CMD} install -y tcpdump
UPDATED_TS="$(cat /var/lib/apt-current/timestamp)"
[ "${UPDATED_TS}" -eq "${CURRENT_TS}" ]

${APT_CMD} remove -y tcpdump
${APT_CMD} install -y tcpdump
CACHED_COUNT=$(($(find /var/cache/apt/archives/ -name "*.deb" | wc -l) + $(find /var/cache/apt/archives/partial/ -name "*.deb" | wc -l)))
[ 0 -eq "${CACHED_COUNT}" ]

# try list cleaning
${APT_CMD} clean-lists
CACHED_COUNT=$(($(find /var/lib/apt/lists/ | wc -l) + $(find /var/lib/apt/lists/partial/ | wc -l)))
[ 3 -eq "${CACHED_COUNT}" ]

echo -e "CLEANUP_DOWNLOADED_LISTS=true\nMAXDELTA=0\n" > /etc/apt-current.conf
${APT_CMD} remove -y tcpdump
${APT_CMD} install -y tcpdump
CACHED_COUNT=$(($(find /var/lib/apt/lists/ | wc -l) + $(find /var/lib/apt/lists/partial/ | wc -l)))
[ 3 -eq "${CACHED_COUNT}" ]

# now it should force the update since the dir is empty, and the install should succeed.
${APT_CMD} remove -y tcpdump
${APT_CMD} install -y tcpdump

${APT_CMD} remove -y --purge tcpdump openssl wget
